name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Check before
      run: |
        echo "event = ${{ github.event }}"
        echo "event_path = ${{ github.event_path }}"
        echo "event_name = ${{ github.event_name }}"
        echo "head_ref = ${{ github.head_ref }}"
        echo "base_ref = ${{ github.base_ref }}"
        echo "event_name = ${{ github.event_name }}"
        ls ~
        ls .
        npm config ls -l
        npm config get cache
    - name: Cache npm packages
      uses: actions/cache@v1
      env:
        cache-name: cache-npm-packages
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Check after
      run: |
        ls ~
        ls .

    - name: Install npm dependencies
      run: |
        npm install

    - name: Run TSLint
      run: |
        npm run lint

    - name: Run Build
      run: |
        npm run build
