name: CI/CD Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache npm packages
      uses: actions/cache@v1
      env:
        cache-name: cache-npm-packages
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Check after
      run: |
        ls /home/runner/.npm

    - name: Install npm dependencies
      run: |
        npm install

    - name: Run Lint
      run: |
        npm run lint

    - name: Run Build
      run: |
        npm run build
