name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build and test with @angular/cli
      run: |
        npm install -g @angular/cli
        npm install
        npm run lint
        npm run build
